name = "Vol"
uuid = "c24d5356-5a15-11e9-33b9-c5868ec50ba3"
authors = ["Felipe Noronha <felipenoris@gmail.com>"]
version = "0.1.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"

[targets]
test = ["Test", "DelimitedFiles"]
